// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ping": {
            "get": {
                "description": "Returns a simple response to test connectivity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "healthcheck"
                ],
                "summary": "Ping the server",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/ping.Response"
                        }
                    }
                }
            }
        },
        "/statistics": {
            "get": {
                "description": "Retrieve time series data in normalized form.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subreddit"
                ],
                "summary": "Retrieve time series data in normalized form.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "name",
                        "name": "subreddit_name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "[",
                        "name": "rank_order_type",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "[",
                        "name": "rank_order_created_within_past",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "1=Minute,2=QuarterHour,3=Hour,4=Daily,5=Mins",
                        "name": "granularity",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/statistics.GetStatisticsResponseBody"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/statistics.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/task": {
            "post": {
                "description": "Schedule a job to get subreddit with the given parameters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subreddit"
                ],
                "summary": "Create a new task to mine subreddit periodically",
                "parameters": [
                    {
                        "description": "Create Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/task.CreateRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/task.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Schedule a job to get subreddit with the given parameters.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subreddit"
                ],
                "summary": "Removes a task",
                "parameters": [
                    {
                        "description": "Delete Request Body",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/task.DeleteRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/task.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "ping.Response": {
            "type": "object"
        },
        "statistics.ErrorResponse": {
            "type": "object"
        },
        "statistics.GetStatisticsResponseBody": {
            "type": "object"
        },
        "task.CreateRequestBody": {
            "type": "object",
            "properties": {
                "interval": {
                    "description": "to be executed every interval [\"hour\"]",
                    "type": "string"
                },
                "items_created_within_past": {
                    "description": "[\"day\",\"hour\",\"month\",\"year\"]",
                    "type": "string"
                },
                "min_item_count": {
                    "description": "Minimum Item Count to retrieve",
                    "type": "integer"
                },
                "order_by": {
                    "description": "[\"top\", \"hot\", \"best\", \"new\"]",
                    "type": "string"
                },
                "subreddit_name": {
                    "description": "Subreddit Name",
                    "type": "string"
                }
            }
        },
        "task.DeleteRequestBody": {
            "type": "object",
            "properties": {
                "subreddit_name": {
                    "type": "string"
                }
            }
        },
        "task.ErrorResponse": {
            "type": "object"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
