definitions:
  ping.Response:
    type: object
  statistics.ErrorResponse:
    type: object
  statistics.GetStatisticsResponseBody:
    type: object
  task.CreateRequestBody:
    properties:
      interval:
        description: to be executed every interval ["hour"]
        type: string
      items_created_within_past:
        description: '["day","hour","month","year"]'
        type: string
      min_item_count:
        description: Minimum Item Count to retrieve
        type: integer
      order_by:
        description: '["top", "hot", "best", "new"]'
        type: string
      subreddit_name:
        description: Subreddit Name
        type: string
    type: object
  task.DeleteRequestBody:
    properties:
      subreddit_name:
        type: string
    type: object
  task.ErrorResponse:
    type: object
info:
  contact: {}
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Returns a simple response to test connectivity
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ping.Response'
      summary: Ping the server
      tags:
      - healthcheck
  /statistics:
    get:
      consumes:
      - application/json
      description: Retrieve time series data in normalized form.
      parameters:
      - description: name
        in: query
        name: subreddit_name
        required: true
        type: string
      - description: '['
        in: query
        name: rank_order_type
        required: true
        type: string
      - description: '['
        in: query
        name: rank_order_created_within_past
        required: true
        type: string
      - description: 1=Minute,2=QuarterHour,3=Hour,4=Daily,5=Mins
        in: query
        name: granularity
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/statistics.GetStatisticsResponseBody'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/statistics.ErrorResponse'
      summary: Retrieve time series data in normalized form.
      tags:
      - subreddit
  /task:
    delete:
      consumes:
      - application/json
      description: Schedule a job to get subreddit with the given parameters.
      parameters:
      - description: Delete Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/task.DeleteRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/task.ErrorResponse'
      summary: Removes a task
      tags:
      - subreddit
    post:
      consumes:
      - application/json
      description: Schedule a job to get subreddit with the given parameters.
      parameters:
      - description: Create Request Body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/task.CreateRequestBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/task.ErrorResponse'
      summary: Create a new task to mine subreddit periodically
      tags:
      - subreddit
swagger: "2.0"
